import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/Layouts/Header'
import { ParamsLng } from '@/i18n/types'

import '@/styles/tailwind.css'
import Main from '@/components/Layouts/Main'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type PropsRootLayout = {
  children: React.ReactNode
} & ParamsLng

export default function Layout({ children, params: { locale } }: Readonly<PropsRootLayout>) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Header />
        <Main>{children}</Main>
      </body>
    </html>
  )
}
