import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { Poppins } from 'next/font/google'
import '@/styles/tailwind.css'

import { ParamsLng } from '@/i18n/types'
const ThemePvd = dynamic(() => import('@/providers/ThemeProvider'), { ssr: false })
import Header from '@/components/Layouts/Header'
import Main from '@/components/Layouts/Main'

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Next 14 typescript',
  description: 'Generated by KhunNoo TML',
}

type PropsRootLayout = {
  children: React.ReactNode
} & ParamsLng

export default function Layout({ children, params: { locale } }: Readonly<PropsRootLayout>) {
  return (
    <html lang={locale}>
      <body className={poppins.className}>
        <ThemePvd>
          <Header />
          <Main>{children}</Main>
        </ThemePvd>
      </body>
    </html>
  )
}
