import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { Poppins } from 'next/font/google'
import '@/styles/tailwind.scss'

import { ParamsLng } from '@/i18n/types'
const Provider = dynamic(() => import('@/app/[locale]/provider'), { ssr: false })
import LayoutAdmin from '@/components/Layouts/Admin'
import LayoutUser from '@/components/Layouts/User'
import { ChildrenByRole } from '@/app/[locale]/provider'

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Next 14 typescript',
  description: 'Generated by KhunNoo TML',
}

type PropsRootLayout = {
  children: React.ReactNode
} & ParamsLng

export default function Layout({ children, params: { locale } }: Readonly<PropsRootLayout>) {
  const isAdmin = true
  return (
    <html lang={locale}>
      <body className={poppins.className}>
        <Provider>
          <ChildrenByRole>{children}</ChildrenByRole>
        </Provider>
      </body>
    </html>
  )
}
